uapi: hyperv: Make underlying struct as packed for a packed union
When trying to use the generated rust bindings for hyperv headers files
we are getting the following error message:

error[E0588]: packed type cannot transitively contain a `#[repr(align)]` type
     --> /mnt/dev/msft/mshv/mshv-bindings/src/bindings.rs:11405:1
      |
11405 | / pub union hv_partition_property_page_access_tracking_config {
11406 | |     pub __bindgen_anon_1: hv_partition_property_page_access_tracking_config__bindgen_ty_1,
11407 | |     pub as_uint64: __u64,
11408 | | }
      | |_^
      |
note: `hv_partition_property_page_access_tracking_config__bindgen_ty_1` has a `#[repr(align)]` attribute
     --> /mnt/dev/msft/mshv/mshv-bindings/src/bindings.rs:11412:1
      |
11412 | / pub struct hv_partition_property_page_access_tracking_config__bindgen_ty_1 {
11413 | |     pub _bitfield_align_1: [u64; 0],
11414 | |     pub _bitfield_1: __BindgenBitfieldUnit<[u8; 8usize]>,
11415 | | }
      | |_^

This means that a packed union contains an unpacked struct which causes a
compilation error when trying to generated mshv-bindings in cloud
hypervisor.

Fixes: 8bc280162b501a (mshv: Add get_gpa_access_state hypercall)

Signed-off-by: Jinank Jain <jinankjain@microsoft.com>
Reviewed-by: Nuno Das Neves <nunodasneves@linux.microsoft.com>
Reviewed-by: Wei Liu <liuwe@microsoft.com>